### ISSUE TITLE
smb bruteforce is crashing

### ISSUE THREAD

**Issue by YoanTLS** [Porchetta-Industries/CrackMapExec#553]
**Describe the bug**
When i use this command : 

`crackmapexec smb 192.1681.1 -u=user.txt -p=user.txt --no-bruteforce --continue-on-success`

The bruteforce goes well with a majority of the accounts, except that at some point, CME crashes. I tried to remove the accounts from the list that could potentially crash CME, but it doesn't change anything.

I think I read that it could crash CME and that you should use the "u=" and "p=" parameters to prevent CME from crashing, but it doesn't seem to work too well. Any solution?

`Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 254, in main
    asyncio.run(
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 102, in start_threadpool
    await asyncio.gather(*jobs)
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 68, in run_protocol
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/cme/protocols/smb.py", line 125, in __init__
    connection.__init__(self, args, db, host)
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 62, in __init__
    self.proto_flow()
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 98, in proto_flow
    if self.login() or (self.username == '' and self.password == ''):
  File "/usr/lib/python3/dist-packages/cme/connection.py", line 235, in login
    for usr, f_pass in zip(user_file, password_file):
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3329: invalid continuation byte
`

**Screenshots**
![image](https://user-images.githubusercontent.com/25932155/158989724-c97bbfd2-a56a-4047-868d-d66945998a29.png)

**Crackmapexec info**
 - OS: Kali 2022.1
 - Version of CME : 5.2.2

**Comment by mpgn** [comment]
Hello, your file is not utf-8 encoded this is why :)
