### ISSUE TITLE
CME wont run

### ISSUE THREAD

**Issue by sailingbikeruk** [Porchetta-Industries/CrackMapExec#715]
**Describe the bug**
CME crashes and gives a trace back error

**To Reproduce**
download current binary cme-ubuntu-latest-3.11.zip
unzip cme-ubuntu-latest-3.11.zip
python3 cme

**Expected behavior**
cme splashscreen appears

**Screenshots**
cme doesnt load, the following traceback error is produced.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/iand/Downloads/cme/__main__.py", line 3, in <module>
  File "/home/iand/Downloads/cme/_bootstrap/__init__.py", line 253, in bootstrap
  File "/home/iand/Downloads/cme/_bootstrap/__init__.py", line 38, in run
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/cme/crackmapexec.py", line 117, in main
    args = gen_cli_args()
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/cme/cli.py", line 76, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/cme/loaders/protocol_loader.py", line 15, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/lib/python3.10/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/cme/protocols/rdp.py", line 11, in <module>
    from aardwolf.commons.factory import RDPConnectionFactory
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/aardwolf/commons/factory.py", line 4, in <module>
    from aardwolf.commons.iosettings import RDPIOSettings
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/aardwolf/commons/iosettings.py", line 1, in <module>
    from aardwolf.extensions.RDPECLIP.channel import RDPECLIPChannel
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/aardwolf/extensions/RDPECLIP/channel.py", line 13, in <module>
    from aardwolf.commons.queuedata import RDP_CLIPBOARD_NEW_DATA_AVAILABLE, RDP_CLIPBOARD_READY, RDPDATATYPE
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/aardwolf/commons/queuedata/__init__.py", line 14, in <module>
    from aardwolf.commons.queuedata.video import RDP_VIDEO
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/aardwolf/commons/queuedata/video.py", line 8, in <module>
    from aardwolf.utils.rectconvert import rectconvert
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/aardwolf/utils/rectconvert.py", line 2, in <module>
    from PIL import Image
  File "/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/home/iand/.shiv/cme_b1eac271535222414e40cfef8c938f5edbee805746e918d26a7cf5f440107ea7/site-packages/PIL/__init__.py)

**Crackmapexec info**
 - OS: Kali 2022.3 kali-rolling (netinstaller)
 - Version of CME - unknown cme won't load.
 - Installed from latest release - cme-ubuntu-latest-3.11.zip

**Additional context**

**Comment by mpgn** [comment]
Which version of python are you using ?

`python3 -v`

**Comment by mpgn** [comment]
Run the binary 3.10 with python version 3.10

**Comment by sailingbikeruk** [comment]
> Which version of python are you using ?
> 
> `python3 -v`

3.10.7

**Comment by sailingbikeruk** [comment]
> Run the binary 3.10 with python version 3.10

thanks. I hadn't linked the two, just downloaded the highest version for the OS

**Comment by sailingbikeruk** [comment]
resolved with the right version matching python version
