### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by RJSOG** [Porchetta-Industries/CrackMapExec#719]
### **Describe the bug**
Can't run crackmapexec because of the following error : "_TypeError: unsupported operand type(s) for |: 'type' and 'type'_" from  _crackmapexec/lib/python3.8/site-packages/aardwolf/extensions/RDPEDYC/vchannels/__init__.py", line 22_

Bug appearsa after à fresh install of cracmapexex by following instructions from and by trying to run crackmapexec for the first time.: https://wiki.porchetta.industries/getting-started/installation/installation-on-unix : **Python Package**

**To Reproduce**
1. Go to 'https://wiki.porchetta.industries/getting-started/installation/installation-on-unix' and follow the **Python Package instructions** .
2. Run `crackmapexec`

**Expected behavior**
Show help message and exit

**Screenshots**
![image](https://user-images.githubusercontent.com/44468960/211634349-8a56505a-bfec-4680-80cf-c476c0f0d0b9.png)

**Crackmapexec info**
 - OS: [WSL - Ubuntu]
 - Version of CME [5.4.1]
 - Installed from Python Package / Github

**Additional context**
*Stack Trace:*
Traceback (most recent call last):
  File "/home/unixjesus/.local/bin/crackmapexec", line 8, in <module>
    sys.exit(main())
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/cme/crackmapexec.py", line 117, in main
    args = gen_cli_args()
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/cme/cli.py", line 76, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/cme/loaders/protocol_loader.py", line 15, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/lib/python3.8/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/cme/protocols/rdp.py", line 11, in <module>
    from aardwolf.commons.factory import RDPConnectionFactory
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/aardwolf/commons/factory.py", line 4, in <module>
    from aardwolf.commons.iosettings import RDPIOSettings
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/aardwolf/commons/iosettings.py", line 5, in <module>
    from aardwolf.extensions.RDPEDYC.channel import RDPEDYCChannel
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/aardwolf/extensions/RDPEDYC/channel.py", line 15, in <module>
    from aardwolf.extensions.RDPEDYC.vchannels import VirtualChannelBase
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/aardwolf/extensions/RDPEDYC/vchannels/__init__.py", line 6, in <module>
    class VirtualChannelBase:
  File "/home/unixjesus/.local/pipx/venvs/crackmapexec/lib/python3.8/site-packages/aardwolf/extensions/RDPEDYC/vchannels/__init__.py", line 22, in VirtualChannelBase
    async def channel_rawdata_in(self, msg:DYNVC_DATA_FIRST | DYNVC_DATA):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Understanding the error**
Error is due to to the unsupported operand '|' which is only available on Python 10.x.x but Python 3.8 is used.

**Fixing the error**
`vim crackmapexec/lib/python3.8/site-packages/aardwolf/extensions/RDPEDYC/vchannels/__init__.py`
at line 22 change:
`async def channel_rawdata_in(self, msg:DYNVC_DATA_FIRST | DYNVC_DATA):` 
to:
`async def channel_rawdata_in(self, msg:DYNVC_DATA_FIRST or DYNVC_DATA):`

**Comment by mpgn** [comment]
Thanks for the report ! fix is on his way

**Comment by mpgn** [comment]
fixed
