### ISSUE TITLE
MacOS pip download --no-binary aardwolf aardwolf error

### ISSUE THREAD

**Issue by ghost** [Porchetta-Industries/CrackMapExec#721]
WARNING: Missing build requirements in pyproject.toml for aardwolf from https://files.pythonhosted.org/packages/3d/9a/61d9e54de2f0b93c6f1dd9a3b8e6526510531e6e64fc7b9724f123c11512/aardwolf-0.2.2.tar.gz.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.

Can someone please tell me what the problem is here and how to fix it?

MacBook Air M2 on Monterey 12.5

**Comment by Bxneyard** [comment]
it is not. crackmapexec works in kali linux arm 64, so in theory i should be able to make this work in mac os too, right? i really want to run this natively.

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/master/Downloads/./cme/__main__.py", line 3, in <module>
  File "/Users/master/Downloads/./cme/_bootstrap/__init__.py", line 253, in bootstrap
  File "/Users/master/Downloads/./cme/_bootstrap/__init__.py", line 38, in run
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/crackmapexec.py", line 117, in main
    args = gen_cli_args()
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/cli.py", line 76, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/loaders/protocol_loader.py", line 15, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/protocols/ldap.py", line 14, in <module>
    from cme.protocols.ldap.kerberos import KerberosAttacks
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/protocols/ldap/kerberos.py", line 10, in <module>
    from impacket.krb5.ccache import CCache
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/impacket/krb5/ccache.py", line 31, in <module>
    from impacket.krb5 import crypto, constants, types
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/impacket/krb5/crypto.py", line 57, in <module>
    from Cryptodome.Cipher import AES, DES3, ARC4, DES
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
  File "/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-darwin.so', Cannot load '_raw_ecb.abi3.so': dlopen(/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so, 0x0006): tried: '/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so' (no such file), '/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so' (no such file), '/Users/master/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), Not found '_raw_ecb.so'

**Comment by Bxneyard** [comment]
> Hello can you check if the binary is working ?
> 
> https://github.com/Porchetta-Industries/CrackMapExec/releases/tag/v5.4.0

it works only on binary 3.9 if i run it as arch -x86_64 python3 cme. no other binary works. why?

**Comment by fsacer** [comment]
also seeing something related to aardwolf building the thing from git with poetry on linux though.

![image](https://user-images.githubusercontent.com/2059352/218103379-4d7844df-a7a5-47fb-b624-c10d392c6593.png)

**Comment by mpgn** [comment]
you are probably using an old version of cme, git pull and retry :)

**Comment by fsacer** [comment]
ah yeah, that's true, had to remove `poetry.lock` file to be able to pull the latest version.
