### ISSUE TITLE
m2 

### ISSUE THREAD

**Issue by gusechuisheng** [Porchetta-Industries/CrackMapExec#773]
./cme --help               
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/SecTools/./cme/__main__.py", line 3, in <module>
  File "/Users/SecTools/./cme/_bootstrap/__init__.py", line 253, in bootstrap
  File "/Users/SecTools/./cme/_bootstrap/__init__.py", line 38, in run
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/crackmapexec.py", line 117, in main
    args = gen_cli_args()
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/cli.py", line 76, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/loaders/protocol_loader.py", line 15, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/protocols/ldap.py", line 14, in <module>
    from cme.protocols.ldap.kerberos import KerberosAttacks
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/cme/protocols/ldap/kerberos.py", line 10, in <module>
    from impacket.krb5.ccache import CCache
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/impacket/krb5/ccache.py", line 31, in <module>
    from impacket.krb5 import crypto, constants, types
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/impacket/krb5/crypto.py", line 57, in <module>
    from Cryptodome.Cipher import AES, DES3, ARC4, DES
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
  File "/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-darwin.so', Cannot load '_raw_ecb.abi3.so': dlopen(/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so, 0x0006): tried: '/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so' (no such file), '/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so' (no such file), '/Users/tange/.shiv/cme_6214063845d2031ca4272a403cd119f241e251b441792efa1460e71669dc2f4a/site-packages/Cryptodome/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), Not found '_raw_ecb.so'

**Comment by NeffIsBack** [comment]
Which OS are you using? Which cme version are you using and how is cme installed?

**Comment by Marshall-Hallenbeck** [comment]
@gusechuisheng Please use the bug template. It's very hard to figure out an issue by just a large stacktrace.
