### ISSUE TITLE
Can't run crackmapexec

### ISSUE THREAD

**Issue by dxrk-kali** [Porchetta-Industries/CrackMapExec#796]
Below is the output from myself running the crackmapexec -v command (I am on Linux kali 6.1.0-kali9-rt-amd64 #1 SMP PREEMPT_RT Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux):

└─# crackmapexec -v
Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 117, in main
    args = gen_cli_args()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cme/cli.py", line 76, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cme/loaders/protocol_loader.py", line 15, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/cme/protocols/smb.py", line 34, in <module>
    from cme.protocols.ldap.smbldap import LDAPConnect
  File "/usr/lib/python3/dist-packages/cme/protocols/ldap/smbldap.py", line 9, in <module>
    from impacket.ldap import ldap as ldap_impacket
  File "/usr/lib/python3/dist-packages/impacket/ldap/ldap.py", line 41, in <module>
    import OpenSSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3253, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

**Comment by dxrk-kali** [comment]
I fixed it, I noticed it found deprecated files, probably because i used apt to reinstall it and my old files didnt get updated so it was using two different codebases. Sorry Devs!

To fix run:
``` pip install --upgrade crackmapexec ```
