### ISSUE TITLE
Error after installation on MAC M2

### ISSUE THREAD

**Issue by M4TxRx** [Porchetta-Industries/CrackMapExec#797]
**Describe the bug**
After installation on MAC M2 I have this error :
`
Traceback`` (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 805, in get
    value = d[option]
            ~^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py", line 1004, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py", line 996, in __missing__
    raise KeyError(key)
KeyError: 'audit_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myname/.local/bin/cme", line 5, in <module>
    from cme.crackmapexec import main
  File "/Users/myname/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/crackmapexec.py", line 17, in <module>
    from cme.config import cme_config, cme_workspace, config_log, ignore_opsec
  File "/Users/myname/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/config.py", line 18, in <module>
    audit_mode = cme_config.get("CME", "audit_mode")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 808, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'audit_mode' in section: 'CME'
`

**Steps to reproduce the behavior:**
git clone https://github.com/mpgn/CrackMapExec
cd CrackMapExec
pipx install . --force
cme

**Crackmapexec info:**
 - OS: MAC OS ARM Version 13.0.1 (22A400)
 - Version of CME 6.0.0
 -  Latest release

**Comment by mpgn** [comment]
can you submit your issue to the new repo https://github.com/mpgn/CrackMapExec ?
